version: '2.1'
services:
  localstack:
    image: localstack/localstack:0.10.5
    ports:
      - "4567-4599:4567-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - DEBUG="true"
      - LAMBDA_EXECUTOR=docker
      - DATA_DIR=/tmp/localstack2
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack2}:/tmp/localstack2"
      - /var/run/docker.sock:/var/run/docker.sock
